version: '3.8'
services:
  haproxy:
    image: netzint/onlyoffice-haproxy:7.1.1
    restart: always
    depends_on:
      - postgresql
      - rabbitmq
      - documentserver
    ports:
      - "443:443"

  documentserver:
    image: netzint/onlyoffice-documentserver:7.1.1
    depends_on:
      - postgresql
      - rabbitmq
    env_file:
      - ./config.env
    expose:
      - '80'
    restart: always
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@rabbitmq
      - SSL_CERTIFICATE_PATH=/etc/ssl/webserver/tls.crt
      - SSL_KEY_PATH=/etc/ssl/webserver/tls.key
      - SSL_DHPARAM_PATH=/etc/ssl/webserver/dhparam.pem
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
    volumes:
      - ./data/data:/var/www/onlyoffice/Data
      - ./data/log:/var/log/onlyoffice
      - ./data/lib:/var/lib/onlyoffice
      - ./data/fonts:/usr/share/fonts

  rabbitmq:
    image: rabbitmq
    restart: always
    expose:
      - '5672'

  redis:
    image: redis
    restart: always
    expose:
      - '6379'

  postgresql:
    image: postgres:9.5
    env_file:
      - ./config.env
    restart: always
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - '5432'
    volumes:
      - ./data/db:/var/lib/postgresql
